filter:
    excluded_paths:
        - docs/*

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=build/report.junit.xml'
                coverage:
                    file: 'report.junit.xml'
                    format: 'clover'
